// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALzdd7qQdemxo4BHN--GRkLZ0GFlbEwLA',
    appId: '1:18417914632:web:9c08693103ccd713d892bd',
    messagingSenderId: '18417914632',
    projectId: 'skillzaar-bcb0f',
    authDomain: 'skillzaar-bcb0f.firebaseapp.com',
    storageBucket: 'skillzaar-bcb0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtG2_o2-9_BrXDCAKikd_83uYGxIDfy30',
    appId: '1:18417914632:android:4cab83b8e1668174d892bd',
    messagingSenderId: '18417914632',
    projectId: 'skillzaar-bcb0f',
    storageBucket: 'skillzaar-bcb0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7zqXeNz4rCbXaIT3Bou1FbYpo0XIKC5A',
    appId: '1:18417914632:ios:9bf6f8f356069c62d892bd',
    messagingSenderId: '18417914632',
    projectId: 'skillzaar-bcb0f',
    storageBucket: 'skillzaar-bcb0f.firebasestorage.app',
    iosBundleId: 'com.skillzaar.worker',
  );

}